IMAGE_VIEWER:
  darwin|mac os:
    'Preview'
  cygwin|mswin|mingw|bccwin|wince|emx|mswin32:
    "explorer"
FILE_EXPLORER:
  darwin|mac os:
    'Finder'
  cygwin|mswin|mingw|bccwin|wince|emx|mswin32:
    "explorer"
TEXT_EDIT:
  darwin|mac os:
    'TextEdit'
  cygwin|mswin|mingw|bccwin|wince|emx|mswin32:
    "notepad"
